name: Build Images

on:
  push:
    branches:
      - buster
      - 'releases/**'
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Version'
jobs:
  version:
    outputs:
      release: ${{ steps.get_version.outputs.release }}
    runs-on: "ubuntu-latest"
    steps:
      - 
        name: Get the release version
        id: get_version
        run: |
          if [ -z "$release" ]
          then
                release=$(date '+%Y%m%d')
                echo release="${release}" >> $GITHUB_OUTPUT
          else
                echo release="${release}" >> $GITHUB_OUTPUT
          fi
        env:
          release: ${{ github.event.inputs.release }}
  build:
    runs-on: ${{ matrix.host }}
    needs: [ version ]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        host: [
          "ubuntu-latest",
          #"macos-10.15",
        ]
        config:
          - {
              name: "Debian buster arm64",
              basefile: "base_buster_arm64",
              compilefile: "compile_buster_arm64",
              finalfile: "final_buster_arm64",
              arch: "arm64",
              osname: "buster",
              ostype: "Debian"
            }
    name:  'Build:  ${{ matrix.config.name }}'
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3.5.3
      - 
        name: Get the version
        id: get_version
        run: |
          if [ -n "$ostype" ]
          then 
                osname=${ostype}_${osname}
          fi
          echo version="${release}-${osname}-${arch}" >> $GITHUB_OUTPUT
          echo release="${release}" >> $GITHUB_OUTPUT
        env:
          release: ${{needs.version.outputs.release }}
          arch: ${{ matrix.config.arch }}
          ostype: ${{ matrix.config.ostype }}
          osname: ${{ matrix.config.osname }}
      - 
        name: Create Base Image
        uses: Nature40/pimod@v0.6.0
        with:
          pifile: ${{ matrix.config.basefile }}.Pifile
      - 
        name: Create Compile Image
        uses: Nature40/pimod@v0.6.0
        with:
          pifile: ${{ matrix.config.compilefile }}.Pifile
      - 
        name: Create Final Image
        uses: Nature40/pimod@v0.6.0
        with:
          pifile: ${{ matrix.config.finalfile }}.Pifile
      - 
        name: Rename Image
        run: mv ${{ matrix.config.finalfile }}.img opendsh-${{ steps.get_version.outputs.version }}.img
      - 
        name: Package zip
        id: packagezip
        run: |
          IMG_FILENAME="opendsh-${{ steps.get_version.outputs.version }}.img"
          ZIP_FILENAME="opendsh-${{ steps.get_version.outputs.version }}.zip"
          SHA256HASHFILE="${IMG_FILENAME}.sha256"
          MD5ZIPHASHFILE="${ZIP_FILENAME}.md5"
          sha256sum "${IMG_FILENAME}" > "${SHA256HASHFILE}"
          zip "${ZIP_FILENAME}" "${IMG_FILENAME}" "${SHA256HASHFILE}"
          md5sum "${ZIP_FILENAME}" > "${MD5ZIPHASHFILE}"
          echo ZIP_FILENAME="${ZIP_FILENAME}" >> $GITHUB_OUTPUT
          echo SHA256HASHFILE="${SHA256HASHFILE}" >> $GITHUB_OUTPUT
          echo MD5ZIPHASHFILE="${MD5ZIPHASHFILE}" >> $GITHUB_OUTPUT
